### ISSUE TITLE
Maybe we need a place for old-version-xbps

### ISSUE THREAD

**Issue by wuhanck** [voidlinux/xbps#244]
I test voidlinux using rpi3.
And find that I cannot install node.js for it require icu-57, but the repo roll to icu-59.
That is a common issues when rolling system broken.
repo.voidlinux don't contain that version at all.
Fortunately, I find that repo2 hold old-version-icu-57(though, it is not in repodata), I can download it and add to a local repo.
And solve the problem.
repo2's meta info don't contain icu-57(only icu-59). I think I am luck that repo2 is not update in time.

So, maybe it is better to setup some repo call old-version-xbps, there is no need to be a repo. it just contain the old-version-xbps for people to download and add to their own local repo to solve issue like that I have meet.

**Comment by Duncaen** [comment]
The repository is already 500GB and we don't receive enough donations to do something like an archive like we had at some point.

The real solution would be to rebuild nodejs to link against the new icu, using an old icu version would requiere many more big packages to use this old version too, it works for you because you only need nodejs and not firefox, chromium, libevent, libreoffice or any other package that would requiere icu.

**Comment by wuhanck** [comment]
sorry.
I will close it.

**Comment by roxma** [comment]
Just curious, is there any chace to implement a feature that xbps will automatically download the source code and build the package when the old version binary cannot be found?

It is interesting to see nix somehow manage to build it from source.
